apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-deployment
spec:
  selector:
    matchLabels:
      app: raptor
  replicas: 1
  template:
    metadata:
      labels:
        app: raptor
    spec:
      containers:
      - name: raptor
        image: superabee/raptor:v0
        imagePullPolicy: Always